server:
  port: 7002

# Eureka配置
eureka:
  instance:
    hostname: localhost  # Eureka服务端的实例名称
  client:
    fetch-registry: false   # fetch-registry如果为false，表示自己是注册中心
    register-with-eureka: false  # 表示是否向eureka注册中心注册自己
    service-url:  # 监控页面
      defaultZone: http://${eureka.instance.hostname}:/${server.port}/eureka/,http://${eureka.instance.hostname}:7001/eureka/,
        http://${eureka.instance.hostname}:7003/eureka/