server:
  port: 3344

spring:
  application:
    name: springcloud-config-server
#    连接远程仓库
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/yingchuanzhou/springcloud-config.git # https,不是git


# 不加这个配置会报Cannot execute request on any known server 这个错：连接Eureka服务端地址不对
# 或者直接注释掉eureka依赖 这里暂时用不到eureka
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

# 通过config-server可以连接到git，访问其中间的资源和配置